/* eslint-disable no-useless-escape */
import { LessonType } from 'entities/lesson'

const LESSONS: LessonType[] = [
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-97291c9d.png',
    socialImageLink: undefined,
    learningActions: 'Transfer crypto into your web3 wallet in order to be ready to interact with DeFi later',
    marketingDescription: 'Move beyond centralized exchanges and start exploring the ever-expanding possibilities of decentralized finance.',
    kudosId: 2562,
    duration: 10,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Understand the basics of decentralized finance.',
    name: 'Intro to DeFi',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '90a9cf9e-e68c-4afc-8d86-6d2574b09d5c',
    slug: 'intro-to-defi'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-5aa84b59.png',
    socialImageLink: undefined,
    learningActions: 'Create and manage your own wallet\nConnect your wallet to a web3 website',
    marketingDescription: 'A crypto wallet is essential gear for Web3 and DeFi. Get basic training on how a wallet works and how to get started.',
    kudosId: 2561,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Create and securely manage your first crypto wallet.',
    name: 'Wallet Basics',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: 'cf1301e7-51ee-4e02-a2d7-2c6cee7a75e6',
    slug: 'wallet-basics'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-71b79973.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: null,
    duration: 5,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Learn how to fund your wallet on L2 via CEXs, third-party onramps, and bridges.',
    name: 'Using Revoke.cash',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'planned',
    featuredOrderOnHomepage: 1,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: 'https://mirror.xyz/banklessacademy.eth/zLajMWXQC44H4uQOXK5j9ROZhuC3xwgoddLtAQQo0k0',
    mirrorNFTAddress: '0x235f3dfe5106f137d8b137c1b7fa115076e8b476',
    notionId: 'fab3fc6b-7411-4e02-86c8-8a458a78caaf',
    slug: 'using-revokecash'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: 'What does it mean to go Bankless? In this lesson, we discuss why millions of people are investing in cryptocurrency - and practical first steps for joining the movement.',
    kudosId: null,
    duration: 10,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'What does it mean to go Bankless? Take your first step, here.',
    name: 'Going Bankless',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'hidden',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '13df8d13-d074-46db-a422-bf8c66c0f73c',
    slug: 'going-bankless'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-71b79973.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: null,
    duration: 5,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Learn how to fund your wallet on L2 via CEXs, third-party onramps, and bridges.',
    name: 'A Guide to Stablecoins',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'planned',
    featuredOrderOnHomepage: 1,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: 'https://mirror.xyz/banklessacademy.eth/zLajMWXQC44H4uQOXK5j9ROZhuC3xwgoddLtAQQo0k0',
    mirrorNFTAddress: '0x235f3dfe5106f137d8b137c1b7fa115076e8b476',
    notionId: 'a0b42523-3a23-4df7-abfb-9c1157eab043',
    slug: 'a-guide-to-stablecoins'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-09017125.png',
    socialImageLink: undefined,
    learningActions: 'Avoid the scams in web3 and keep your assets safe.',
    marketingDescription: '',
    kudosId: 2565,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Protect yourself and your wallet from the most common scams in web3.',
    name: 'Web3 Security',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '3242d8f8-549b-41f6-b376-3bbd831669fc',
    slug: 'web3-security'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-03a3e86a.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: 14067,
    duration: null,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'For testing purposes only',
    name: 'Kudos testing',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'hidden',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '5179bd81-3d39-4eec-8b8e-67f4a1ff0b4e',
    slug: 'kudos-testing'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-dcff6ea3.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: 14611,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Understand how Layer 1 blockchains work - and learn their limitations!',
    name: 'Layer 1 Blockchains',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '3b785456-81f2-4958-97c1-dfb17f19db1f',
    slug: 'layer-1-blockchains'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-c84db284.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: 'Blockchains make cryptocurrency, DeFi, and Web3 possible. Discover how blockchain networks are built and how they work.',
    kudosId: 2563,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Learn about the fundamental architecture of blockchain technology.',
    name: 'Blockchain Basics',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '2eb7b028-211c-49fe-890e-7c3551026b83',
    slug: 'blockchain-basics'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: null,
    duration: null,
    learnings: undefined,
    difficulty: 'Easy',
    description: '',
    name: 'ENS article',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'hidden',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '3fc1b46d-8bc2-4fa4-ba4c-2f79e4c7afb9',
    slug: 'ens-article'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: null,
    duration: null,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Learn how to create and associate an ENS Subname to an address',
    name: 'ENS Subname',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'hidden',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: '76d93164-7e04-426c-932a-d1c1e7ea42b2',
    slug: 'ens-subname'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-71b79973.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: null,
    duration: 5,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Learn how to fund your wallet on L2 via CEXs, third-party onramps, and bridges.',
    name: 'How to Fund a Wallet on Layer 2',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: 1,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: 'https://mirror.xyz/banklessacademy.eth/zLajMWXQC44H4uQOXK5j9ROZhuC3xwgoddLtAQQo0k0',
    mirrorNFTAddress: '0x235f3dfe5106f137d8b137c1b7fa115076e8b476',
    notionId: 'cf70f37e-979e-47c2-8487-ff2a187a5f99',
    slug: 'how-to-fund-a-wallet-on-layer-2'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-755fe7a3.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: 2564,
    duration: 10,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Join the conversation in our Bankless Explorer Community.',
    name: 'Academy Community',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'hidden',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: 'a2c5f9d5-a188-4fa0-b69f-a73a8599a311',
    slug: 'academy-community'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-39d1fc1c.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: '',
    kudosId: 2608,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Dive into DEX Aggregators, liquidity, and the DeFi exchange landscape.',
    name: 'DEX Aggregators',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: 3,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: 'e4db9d0b-47db-4dc5-96ba-707f92003632',
    slug: 'dex-aggregators'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '/lesson/undefined/lesson-29da6288.png',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: 'The Layer 2 revolution has begun. Discover how the Layer 2 ecosystem can boost your transaction speed & reduce gas fees.',
    kudosId: 14886,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Join the Layer 2 ecosystem to boost your transaction speed & reduce fees.',
    name: 'Layer 2 Blockchains',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'publish',
    featuredOrderOnHomepage: 2,
    isCommentsEnabled: false,
    endOfLessonRedirect: 'https://tally.so/r/mZ8orv',
    endOfLessonText: 'To learn more about Optimism and to give feedback about this lesson, click Next.',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: 'd79c7a05-e4b5-454f-87ed-97cc0dbdb0e1',
    slug: 'layer-2-blockchains'
  },
  {
    '0': 'K',
    '1': 'u',
    '2': 'd',
    '3': 'o',
    '4': 's',
    '5': ' ',
    '6': 'i',
    '7': 'm',
    '8': 'a',
    '9': 'g',
    '10': 'e',
    lessonImageLink: '',
    socialImageLink: undefined,
    learningActions: '',
    marketingDescription: 'DEXs and AMMs have changed the landscape of traditional market trading. It’s time to understand why, and how you can use this technology to your own advantage.',
    kudosId: null,
    duration: 15,
    learnings: undefined,
    difficulty: 'Easy',
    description: 'Discover how smart-contract exchanges enable permissionless token swaps!',
    name: 'Decentralized Exchanges',
    moduleId: undefined,
    quest: 'gBdL',
    publicationStatus: 'planned',
    featuredOrderOnHomepage: null,
    isCommentsEnabled: false,
    endOfLessonRedirect: null,
    endOfLessonText: '',
    mirrorLink: null,
    mirrorNFTAddress: '',
    notionId: 'a47ce4a5-6233-4e47-819d-9760c7336daa',
    slug: 'decentralized-exchanges'
  }
]

export default LESSONS
